"use client";

import { 
  Send, Mic, Paperclip, Smile, Volume2, 
  Trash2, Globe, Sparkles, Bot
} from "lucide-react";
import { useState } from "react";

export default function ChatPage() {
  const [message, setMessage] = useState("");

  return (
    <div className="max-w-5xl mx-auto h-[calc(100vh-160px)] flex flex-col">
      {/* Chat Header */}
      <div className="bg-white rounded-t-[2rem] border border-gray-100 p-6 flex items-center justify-between shadow-sm">
         <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-[#1e5128] rounded-2xl flex items-center justify-center text-white">
               <Bot className="w-7 h-7" />
            </div>
            <div>
               <h2 className="text-lg font-bold text-gray-900">AI Krishi Expert</h2>
               <p className="text-[10px] font-black uppercase text-emerald-500 flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse" />
                  Online & Active
               </p>
            </div>
         </div>

         <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 bg-gray-50 border border-gray-100 rounded-xl px-4 py-2">
               <Globe className="w-4 h-4 text-gray-400" />
               <select className="bg-transparent text-sm font-bold text-gray-700 outline-none appearance-none">
                  <option>Hindi (हिन्दी)</option>
                  <option>English</option>
                  <option>Marathi</option>
               </select>
            </div>
            <button className="p-2.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-all">
               <Trash2 className="w-5 h-5" />
            </button>
         </div>
      </div>

      {/* Messages Area */}
      <div className="flex-1 bg-white border-x border-gray-100 p-8 overflow-y-auto space-y-8 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:20px_20px]">
         <div className="flex flex-col items-start gap-2">
            <div className="flex items-center gap-2 mb-1">
               <div className="w-6 h-6 bg-[#1e5128] rounded-md flex items-center justify-center text-white scale-75">
                  <Bot className="w-4 h-4" />
               </div>
            </div>
            <div className="bg-gray-50 border border-gray-100 p-5 rounded-2xl rounded-tl-none max-w-2xl text-gray-700 font-medium shadow-sm relative group">
               Namaste Rajesh! I'm your Krishi Expert. How can I help you with your farm today?
               <div className="flex items-center gap-4 mt-3 text-[10px] font-bold text-gray-400 uppercase">
                  09:00 AM
                  <button className="hover:text-emerald-500 transition-colors">
                     <Volume2 className="w-3.5 h-3.5" />
                  </button>
               </div>
            </div>
         </div>
      </div>

      {/* Input Area */}
      <div className="bg-white rounded-b-[2rem] border border-gray-100 p-6 shadow-sm">
         <div className="flex items-center gap-4 bg-gray-50 border border-gray-100 rounded-2xl px-6 py-2 shadow-inner">
            <button className="text-gray-400 hover:text-[#1e5128] transition-colors">
               <Paperclip className="w-5 h-5" />
            </button>
            <input 
              type="text" 
              placeholder="Type your question..." 
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              className="flex-1 bg-transparent border-none py-4 text-sm font-medium focus:ring-0 placeholder:text-gray-400"
            />
            <div className="flex items-center gap-4 border-l border-gray-200 pl-4">
               <button className="text-gray-400 hover:text-[#1e5128] transition-colors">
                  <Smile className="w-5 h-5" />
               </button>
               <button className="text-[#1e5128] hover:scale-110 transition-transform">
                  <Mic className="w-5 h-5" />
               </button>
               <button className="w-10 h-10 bg-[#1e5128] text-white rounded-xl flex items-center justify-center hover:bg-[#194322] transition-all shadow-lg shadow-emerald-900/10">
                  <Send className="w-5 h-5" />
               </button>
            </div>
         </div>
         <p className="text-center text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-6">
            <Sparkles className="w-3 h-3 inline mr-2 opacity-50" />
            This expert advice is generated by AI and should be verified locally.
         </p>
      </div>
    </div>
  );
}
